
CREATE DATABASE db;
\connect db

CREATE TABLE events (
  timestamp timestamp,
  type CHAR(16),
  payload CHAR(256),
  ip_address CHAR(16));

ALTER USER "postgres" WITH PASSWORD 'master';
CREATE USER "writer" WITH PASSWORD 'writer';
CREATE USER "reader" WITH PASSWORD 'reader';

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM "writer";
GRANT SELECT,UPDATE,INSERT ON ALL TABLES IN SCHEMA public TO "writer";
ALTER DEFAULT PRIVILEGES FOR USER "writer" IN SCHEMA public GRANT SELECT,UPDATE,INSERT ON TABLES TO "writer";

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM "reader";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "reader";
ALTER DEFAULT PRIVILEGES FOR USER "reader" IN SCHEMA public GRANT SELECT ON TABLES TO "reader";
